### ISSUE TITLE
Members cursor query throws error when no more records

### ISSUE THREAD

**Issue by kburnell** [ThatConference/that-api-members#49]
Members cursor works all good until I get to what appears to be the last cursor that should return no more records.

Cursor: dGhvbWFzfHwyMDIwLTAzLTAxVDA0OjEzOjE0Ljg0MFo=

Error: {
  "errors": [
    {
      "message": "Cannot read property 'firstName' of undefined",
      "path": [
        "members",
        "members"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "Members",
        "query": "query($after:String){members{members(after:$after orderBy:FIRSTNAME pageSize:20){cursor members{id firstName lastName profileSlug jobTitle company profileImage}}}}",
        "variables": {
          "after": "dGhvbWFzfHwyMDIwLTAzLTAxVDA0OjEzOjE0Ljg0MFo="
        }
      }
    }
  ],
  "data": {
    "members": {
      "members": null
    }
  }
}

**Comment by brettski** [comment]
corrected with https://github.com/ThatConference/that-api-members/pull/50
